### ISSUE TITLE
Corrupted Skynest IN/OUT identification problem

### ISSUE THREAD

**Issue by xmitan** [michengs/tera-guide#1]
Hi. The color debuff doesn't seem to work correctly most of the time after the update in our server after maintenance. When it says inner fire IN when you go IN, you still die and vice versa. Is there an update about this? Thank you!

**Comment by HackeRsxDD** [comment]
only in fire is the fault ... when you are with the fire buff you have to do the opposite of what the guide says .... sad :(

**Comment by akamech4n** [comment]
no, happen with ice too
this problem its probably something with wings glow
