### ISSUE TITLE
CSNM/HM Issue after patch 95.3

### ISSUE THREAD

**Issue by AshantyTTV** [michengs/tera-guide#3]
Sometimes IN/OUT is reversed ... Its make calls IN and its OUT or vice-versa. Can you update it for this patch pls?

**Comment by justkeepquiet** [comment]
We provide changes for fix this problem https://github.com/michengs/tera-guide/pull/4

@AshantyTTV also you can use fixed version of this guide here https://github.com/hsdn/tera-guide

**Comment by Nullaris-Dev** [comment]
Thanks @shindmitry tons of beers for you.

**Comment by michengs** [comment]
try to use this https://github.com/michengs/Dungeon-guide
